### ISSUE TITLE
Support including message/stack traces in detailed summary report

### ISSUE THREAD

**Issue by raido** [mikepenz/action-junit-report#1039]
Hello!

In current implementation stack traces are used as fallback message for the failure, when there's no failure `message` attribute present. 

https://github.com/mikepenz/action-junit-report/blob/main/src/testParser.ts#L330

However it might be useful to include stack traces in detailed summary report. For example with additional configuration option.

Example:

```yml
- name: Publish Test Report
  uses: mikepenz/action-junit-report@v4
  if: always()
  with:
    detailed_summary: true
    detailed_summary_include_stacktraces: true
```

Also if it would be possible to include exact error/failure message in detailed summary report, could be helpful to understand which assertion exactly has failed.
