### ISSUE TITLE
Annotations not being added to files when there are more than 50 failures

### ISSUE THREAD

**Issue by nfelt14** [mikepenz/action-junit-report#1063]
I have a PR that I am manipulating to force more than 50 failures on. Not all files that should have annotations are getting them.

https://github.com/nfelt14/tm_devices/pull/10

My settings are here:
```
      - name: Publish Test Results
        id: test-results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: artifacts/**/.results_tests/results.xml
          check_name: Test Results
          require_tests: true
          update_check: true
          check_annotations: true
          annotate_only: true
          job_summary: true
```

These are the permissions I am using:
```
    permissions:
      checks: write
      pull-requests: write
      actions: read
      contents: read
```
