### ISSUE TITLE
check_name failed to report

### ISSUE THREAD

**Issue by hikoukii-gumoo** [mikepenz/action-junit-report#1089]
I setup a check rule on a action-junit-report with check_name:
```     
name: Report
uses: mikepenz/action-junit-report@v4
if: success() || failure()
with:
    check_name: ci/unit-test
    report_paths: ./unit-test-reports/**/TEST-*.xml
```

The check is flaky, sometimes it passed, sometimes it stucks forever:

```
ci/unit-test Expected — Waiting for status to be reported
```

Log:
```
Run mikepenz/action-junit-report@v4
📘 Reading input values
📦 Process test results
🚀 Publish results
  ℹ️ - ci/unit-test - 113 tests run, 113 passed, 0 skipped, 0 failed.
  ℹ️ - ci/unit-test - Creating check (Annotations: 0)
  ⚠️ No annotations found for ci/unit-test. If you want to include passed results in this table please configure 'include_passed' as 'true'
```

I'm using latest runner version.
Am I missing any configuration or it's a bug of action-junit-report?
