### ISSUE TITLE
Suggestion: provide info on setting --max_old_space_size

### ISSUE THREAD

**Issue by arcuri82** [mikepenz/action-junit-report#1170]
Hi,
 thx for this action.
Recently, it started to fail due to:

`FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

I have thousands of tests...

the solution was to use `max_old_space_size`, eg, currently I am using:

```
      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v4
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
```

maybe something worthy to mention in the documentation, in case other users end up in the same problem.

This is base on [this discussion](https://github.com/actions/runner-images/issues/70).
