### ISSUE TITLE
Unexpected input(s) 'comment'

### ISSUE THREAD

**Issue by kjetilk-kontali** [mikepenz/action-junit-report#1186]
Hi,

I've added the GitHub Action as follows:

```
- name: Publish Test Report for Integration Tests
  uses: mikepenz/action-junit-report@v4
  if: always()
  with:
    report_paths: '.test-results/*.xml'
    detailed_summary: true
    comment: true
    include_passed: true
```

But when the action is run, I get the following warning:
`Warning: Unexpected input(s) 'comment', valid inputs are ['token', 'github_token', 'report_paths', 'test_files_prefix', 'exclude_sources', 'suite_regex', 'annotate_only', 'check_annotations', 'update_check', 'check_name', 'commit', 'fail_on_failure', 'require_tests', 'require_passed_tests', 'include_passed', 'check_title_template', 'summary', 'check_retries', 'transformers', 'job_summary', 'detailed_summary', 'annotate_notice', 'follow_symlink', 'job_name', 'annotations_limit', 'truncate_stack_traces']`

I can see from the docs (and the source code) that `comment` should be a valid input argument to the GH Action, so why am I getting this warning?
