### ISSUE TITLE
require_tests=false sending a failure when no tests are found

### ISSUE THREAD

**Issue by ennoucas** [mikepenz/action-junit-report#119]
Hello, `require_tests` is not working for me. It's still sending a failure when I don't provide a test file (`scanner.xml`) (which is the case when no errors are found)

Here's my config: 
```yaml
            - name: Print Security Scanner Results
              uses: mikepenz/action-junit-report@v2
              with:
                  report_paths: '**/scanner.xml'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  check_name: PMD Security Report Scanner
                  fail_on_failure: true
                  require_tests: false
```
Action output: 
📦 Process test results
  ℹ️ No test results found!
  ℹ️ Posting status 'completed' with conclusion 'failure' to ...
