### ISSUE TITLE
JUnit Test Report job does not appear in the workflow run

### ISSUE THREAD

**Issue by liyaka** [mikepenz/action-junit-report#1234]
Hi, we have a strange behavior that started lately - when there are failed tests,  JUnit Test Report job does not appear in the workflow run:
![Screenshot 2024-11-11 at 18 32 58](https://github.com/user-attachments/assets/9d404af2-50a0-48bc-902c-f3b6b3c771b2)

We do get the summary, but no not job where we can see the details and the logs
![Screenshot 2024-11-11 at 18 33 17](https://github.com/user-attachments/assets/baca6b6b-5aa7-4ee1-9f45-55506a11cb14)

The way we expect it to work is this (it used to work like this, nothing is changed in our configuration):
![Screenshot 2024-11-11 at 18 19 59](https://github.com/user-attachments/assets/fe3c99db-5cae-4b52-87a3-dab21ab3a689)

the configuration is simple:
```
- name: Publish Test Report
          uses: mikepenz/action-junit-report@v4
          if: success() || failure() # always run even if the previous step fails
          with:
            report_paths: 'report.xml'
            fail_on_failure: true
            summary: true
            detailed_summary: true
```
