### ISSUE TITLE
Since updating to mikepenz/action-junit-report@v5 the action is very slow

### ISSUE THREAD

**Issue by ext** [mikepenz/action-junit-report#1251]
Often the step taking two hours or longer.

![image](https://github.com/user-attachments/assets/eaa6e5d3-0615-4afc-a7a1-7fa05c9d42fd)

Link to job: https://github.com/Forsakringskassan/designsystem/actions/runs/12059916705/job/33629384261
Link to Renovate PR bumping the version: https://github.com/Forsakringskassan/designsystem/pull/118

The step is defined as:

```
            - name: Publish test results
              if: github.event_name == 'push' && (success() || failure())
              uses: mikepenz/action-junit-report@v5
              with:
                  report_paths: "packages/*/test-results/jest-junit.xml"
                  include_passed: true
                  check_name: Jest
```

It could be an error in our configuration but in that case I'm not really sure what.
