### ISSUE TITLE
Error when enabling comments (requires a valid issue number)

### ISSUE THREAD

**Issue by afucher** [mikepenz/action-junit-report#1330]
When enabling the option to add comment, it gives me the following error:

```
Action requires a valid issue number (PR reference) to be able to attach a comment..
```

```
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          simplified_summary: true
          comment: true
````
