### ISSUE TITLE
Merge reports of multiple checks

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/action-junit-report#195]
Running many checks with different `check_name` will result in the sidebar to contain all those entries. 

It would be great if we could merge together the report so only one entry will be shown 

Suggested by @iBotPeaches in this ticket:
https://github.com/mikepenz/action-junit-report/issues/194

**Comment by mbien** [comment]
github recently added job summaries:
https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

this reads like it might solve this problem too. (also requires less permissions as bonus)

**Comment by mikepenz** [comment]
You may want to try the following [PR](https://github.com/mikepenz/action-junit-report/pull/606/) which adds ability configure multiple imports in one step:

```yml
      - name: Test Multi test import
        uses: ./
        if: endsWith(github.ref, 'main') == false
        with:
          check_name: |-
            Example Multi JUnit Test Report
            Example Multi Pytest Report
          report_paths: |-
            **/surefire-reports/TEST-*.xml
            test_results/python/report.xml
          summary: |-
            <table><thead><tr><th> Application (src/applications) </th></tr></thead><tbody><tr><td> multi test </td></tr></tbody></table>
            \n
          check_title_template: |-
            {{SUITE_NAME}} | {{TEST_NAME}}
            \n
```

https://github.com/mikepenz/action-junit-report/pull/606/
