### ISSUE TITLE
Testsuites are not displayed

### ISSUE THREAD

**Issue by dwertent** [mikepenz/action-junit-report#518]
Hi :)

I'm looking for a plugin for parsing junit results on github actions and I noticed the testsuites and testsuite are not displayed.

junit.xml ->
```
<testsuites errors="0" disabled="0" failures="1" tests="1" time="" name="">
	<testsuite name="apps/v1//Deployment/example" disabled="0" errors="0" failures="1" hostname="" id="1" skipped="" time="" timestamp="0001-01-01 00:00:00 +0000 UTC">
		<properties>
			<property name="ID" value="apps/v1//Deployment/example">
			</property>
		</properties>
		<testcase classname="C-0061" status="failed" name="Pods in default namespace" time="">
			<failure message="metadata.namespace=YOUR_VALUE" type="">
				More deatiles: https://hub.armo.cloud/docs/c-0061
			</failure>
		</testcase>
		<testcase classname="C-0044" status="passed" name="Container hostPort" time="">
		</testcase>
	</testsuite>
</testsuites>
```
Github action:
```
# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: JUnit Report Action
        # uses: mikepenz/action-junit-report@127c778ac944abc0f48a5103964304bab7eb208b
        uses: mikepenz/action-junit-report@v2.9.1
        with:
          report_paths: "junit.xml"
```

Result:

![image](https://user-images.githubusercontent.com/64066841/155984882-158aa5a6-58e3-4e04-9c21-7e6b84b79eca.png)

The testsuite information is totally missing, is this behavior intended or a bug?
