### ISSUE TITLE
Regression after 3.3.3?

### ISSUE THREAD

**Issue by ohmer** [mikepenz/action-junit-report#682]
Hi there,

I am using this action with reports produced by [container-structure-test](https://github.com/GoogleContainerTools/container-structure-test). I have a workflow running daily which stopped working about the same time as 3.4.0 was released (early september):

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1216016/192039313-cc78421c-ddc1-477c-b3cc-aa6e0eaf77ea.png">

Here is the relevant part of my workflow:

```yaml
      - name: Test image
        run: |
          curl -sSLO https://storage.googleapis.com/container-structure-test/v1.11.0/container-structure-test-linux-${{ matrix.architecture.docker }}
          mv container-structure-test-linux-${{ matrix.architecture.docker }} container-structure-test
          chmod +x container-structure-test

          ./container-structure-test test \
            --image ${{ github.repository }}:test \
            --config tests/container-structure-test.yaml \
            --output junit \
            --test-report tests/container-structure-test.xml

      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: Container structure test report (${{ matrix.architecture.docker }})
          report_paths: tests/container-structure-test.xml
```

Pinning to version 3.3.3, it works again therefore I suspect a regression.

I can produce the report locally, here it is:

```xml
<testsuites failures="0" tests="8" time="1967986371">
    <testsuite>
        <testcase name="Command Test: apt-get upgrade" time="999638317"></testcase>
        <testcase name="Command Test: Commands in $PATH" time="968348054"></testcase>
        <testcase name="File Existence Test: /home/app/investapp" time="0"></testcase>
        <testcase name="File Existence Test: /home/app/investapp/db" time="0"></testcase>
        <testcase name="File Existence Test: /home/app/investapp/log" time="0"></testcase>
        <testcase name="File Existence Test: /home/app/investapp/tmp" time="0"></testcase>
        <testcase name="File Existence Test: /home/app/investapp/permanent_directory" time="0"></testcase>
        <testcase name="Metadata Test" time="0"></testcase>
    </testsuite>
</testsuites>
```
