### ISSUE TITLE
check title name {{ FILE_NAME }} is not working

### ISSUE THREAD

**Issue by hlolli** [mikepenz/action-junit-report#692]
Thanks a lot for this plugin, we the csound developers have been using it for almost two years now 🙏 

We are now extending our tests and are experiencing an issue.
the file name macro appears empty here https://github.com/csound/csound/actions/runs/3169515183
but I did include it here as it was listed in the manual https://github.com/csound/csound/blob/ead287fdedb7334c3e16c1b2bd9e028b9792295e/.github/workflows/csound_wasm.yml#L113-L114
perhaps you can see if I've configured it incorrectly, but the files are picked up from the filepath glob, and I'd assume the filenames are known?

Thanks again!

**Comment by mikepenz** [comment]
In a quick look over the provided code I don't see anything suspicious. 

The code responsible for replacing the pattern is found here: https://github.com/mikepenz/action-junit-report/blob/7e977792727942c3091dd66d60469d9944b43b97/src/testParser.ts#L316-L321

Could you possibly provide a simplified junit export so I can reproduce in the test-cases. Thank you.

**Comment by mikepenz** [comment]
@hlolli I'd appreciate if you could please provide additional input on the ticket.

**Comment by mikepenz** [comment]
Closing this ticket due to inactivity, please report back to reopen.

**Comment by Mqxx** [comment]
I have a similar issue. When using `transformers` in combination with `check_title_template` the `{{FILE_NAME}}` does not get resolved correctly and gets filled with the none replaced variant, at least for the summary. When looking into the console logs, it gets replaced correctly.

```yml
      - name: 'Publish test report'
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: 'artifacts/${{ env.TEST_REPORT_NAME }}'
          detailed_summary: true
          group_suite: true
          include_passed: true
          annotate_notice: true
          transformers: '[{"searchValue": "${{ github.workspace }}", "replaceValue": ""}]'
          check_title_template: '{{FILE_NAME}} | {{TEST_NAME}}'
```

That's how it looks in the summary:

<img width="1002" height="273" alt="Image" src="https://github.com/user-attachments/assets/2756a0ad-7d7a-46e8-a3c5-cc3228a21240" />

But the console looks correct:

<img width="466" height="168" alt="Image" src="https://github.com/user-attachments/assets/257f8af9-e9e0-492a-bd8c-8e149d003e5c" />

<img width="531" height="175" alt="Image" src="https://github.com/user-attachments/assets/b7d3e27c-7063-42f0-9218-caf4f263a42d" />

Not sure why its only in the summary, but yea.
