### ISSUE TITLE
fail_on_failure = false marks the step as failed when a test fails

### ISSUE THREAD

**Issue by fasmat** [mikepenz/action-junit-report#699]
I have a job that runs unit tests. Some of these tests fail. I have the following step in my job:

```yaml
- name: Publish Test Report
  uses: mikepenz/action-junit-report@v3
  if: always()
  with:
    report_paths: "**/unit-tests.xml"
    fail_on_failure: false
```

This step fails when any test in `unit-tests.xml` failed, although `fail_on_failure` is set to `false`.
