### ISSUE TITLE
require_tests flag is not working

### ISSUE THREAD

**Issue by fjbenitog** [mikepenz/action-junit-report#802]
I have seen that this flag was fixed, but I am using this configuration

```yaml
      - name: Test Reports
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: "Test Reports - Scala: ${{ matrix.scala }} | Java: ${{ matrix.java }}"
          require_tests: false
          report_paths: 'dist/test/reports/**/*.xml'
```
And I still have an error when I don't have tests
