### ISSUE TITLE
Check Run Not Created when update_check: true

### ISSUE THREAD

**Issue by ShahroZafar** [mikepenz/action-junit-report#927]
I have the following configuration in my workflow

```
  - name: Publish Test Report
    uses: mikepenz/action-junit-report@v3
    if: ${{ !cancelled() }}
    with:
      report_paths: '**/target/test-reports/*.xml'
      detailed_summary: true
      update_check: true
```

I am using `update_check` as the number of annotations can be more than 50. When I have `update_check`: `true` it doesn't create the job `JUnit Test Report`.

Looking at the logs of the step shows this error

```
Error: ❌ Failed to create checks using the provided token. (TypeError: Cannot read properties of undefined (reading 'id'))
```

I have the following permissions in place for the workflow

```
permissions:
  id-token: write
  contents: read
  checks: write
```

The workflow works fine and create the job `JUnit Test Report` when `update_check` is false
